stages:
  - frontend-build-test
  # - frontend-unit-test
  # - backend-build-test
  # - backend-unit-test

frontend-build-test:
  stage: frontend-build-test
  script:
    - cd builds/Seasonfarm/ClientApp/
    - npm install
    - npm run test
    - npm run build
