stages:
  - frontend-build-test
  # - frontend-unit-test
  # - backend-build-test
  # - backend-unit-test

frontend-build-test:
  image: node:10
  stage: frontend-build-test
  script:
    - cd Seasonfarm/ClientApp/
    - npm install
    - npm run test
    - npm run build
